security:
    enable_authenticator_manager: true

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
#            login_throttling:
#                max_attempts: 5
            json_login:
                username_path: user
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login,                       roles: PUBLIC_ACCESS }
        - { path: ^/api/user,                        roles: IS_AUTHENTICATED_FULLY }
